=head1 NAME

Smokeping::probes::CiscoRTTMonTcpConnect - Probe for SmokePing

=head1 SYNOPSIS

 *** Probes ***

 +CiscoRTTMonTcpConnect

 forks = 5
 offset = 50%
 step = 300
 timeout = 15

 # The following variables can be overridden in each target section
 ioshost = RTTcommunity@Myrouter.foobar.com.au # mandatory
 iosint = 10.33.22.11
 pings = 5
 port = 80
 tos = 160

 # [...]

 *** Targets ***

 probe = CiscoRTTMonTcpConnect # if this should be the default probe

 # [...]

 + mytarget
 # probe = CiscoRTTMonTcpConnect # if the default probe is something else
 host = my.host
 ioshost = RTTcommunity@Myrouter.foobar.com.au # mandatory
 iosint = 10.33.22.11
 pings = 5
 port = 80
 tos = 160

=head1 DESCRIPTION

A probe for smokeping, which uses the ciscoRttMon MIB functionality ("Service Assurance Agent", "SAA") of Cisco IOS to measure TCP connect times between a Cisco router and a TCP server. The measured value is the time is the time to establish a TCP session, i.e. the time between the initial "SYN" TCP packet of the router and the "SYN ACK" packet of the host. The router terminates the TCP session immediately after the reception of "SYN ACK" with a "FIN" packet.

=head1 VARIABLES

Supported probe-specific variables:

=over

=item forks

Run this many concurrent processes at maximum

Example value: 5

Default value: 5

=item offset

If you run many probes concurrently you may want to prevent them from
hitting your network all at the same time. Using the probe-specific
offset parameter you can change the point in time when each probe will
be run. Offset is specified in % of total interval, or alternatively as
'random', and the offset from the 'General' section is used if nothing
is specified here. Note that this does NOT influence the rrds itself,
it is just a matter of when data acqusition is initiated.
(This variable is only applicable if the variable 'concurrentprobes' is set
in the 'General' section.)

Example value: 50%

=item step

Duration of the base interval that this probe should use, if different
from the one specified in the 'Database' section. Note that the step in
the RRD files is fixed when they are originally generated, and if you
change the step parameter afterwards, you'll have to delete the old RRD
files or somehow convert them. (This variable is only applicable if
the variable 'concurrentprobes' is set in the 'General' section.)

Example value: 300

=item timeout

How long a single 'ping' takes at maximum

Example value: 15

Default value: 5

=back

Supported target-specific variables:

=over

=item ioshost

The (mandatory) ioshost parameter specifies the Cisco router, which will
establish the TCP connections as well as the SNMP community string on
the router.

Example value: RTTcommunity@Myrouter.foobar.com.au

This setting is mandatory.

=item iosint

The (optional) iosint parameter is the source address for the TCP
connections. This should be one of the active (!) IP addresses of the
router to get results. IOS looks up the target host address in the
forwarding table and then uses the interface(s) listed there to send
the TCP packets. By default IOS uses the (primary) IP address on the
sending interface as source address for a connection.

Example value: 10.33.22.11

=item pings

How many pings should be sent to each target, if different from the global
value specified in the Database section. Note that the number of pings in
the RRD files is fixed when they are originally generated, and if you
change this parameter afterwards, you'll have to delete the old RRD
files or somehow convert them.

Example value: 5

=item port

The (optional) port parameter lets you configure the destination TCP
port on the host. The default is the http port 80.

Default value: 80

=item tos

The (optional) tos parameter specifies the value of the ToS byte in the
IP header of the packets from the router. Multiply DSCP values times 4
and Precedence values times 32 to calculate the ToS values to configure,
e.g. ToS 160 corresponds to a DSCP value 40 and a Precedence value of
5. Please note that this will not influence the ToS value in the packets
sent by the the host.

Example value: 160

Default value: 0

=back


=head1 AUTHORS

Joerg.Kummer at Roche.com 

=head1 NOTES

=head2 IOS VERSIONS

This probe only works with Cisco IOS 12.0(3)T or higher. It is recommended to test it on less critical routers first. 

=head2 INSTALLATION

To install this probe copy ciscoRttMonMIB.pm to ($SMOKEPINGINSTALLDIR)/Smokeping/lib and CiscoRTTMonTcpConnect.pm to ($SMOKEPINGINSTALLDIR)/lib/Smokeping/probes. V0.97 or higher of Simon Leinen's SNMP_Session.pm is required.

The router(s) must be configured to allow read/write SNMP access. Sufficient is:

	snmp-server community RTTCommunity RW
 
If you want to be a bit more restrictive with SNMP write access to the router, then consider configuring something like this 

	access-list 2 permit 10.37.3.5
	snmp-server view RttMon ciscoRttMonMIB included
	snmp-server community RTTCommunity view RttMon RW 2

The above configuration grants SNMP read-write only to 10.37.3.5 (the smokeping host) and only to the ciscoRttMon MIB tree. The probe does not need access to SNMP variables outside the RttMon tree.

=head1 BUGS

The probe establishes unnecessary connections, i.e. more than configured in the "pings" variable, because the RTTMon MIB only allows to set a total time for all connections in one measurement run (one "life"). Currently the probe sets the life duration to "pings"*2+3 seconds (2 secs is the timeout value hardcoded into this probe). 

=head1 SEE ALSO

L<http://oss.oetiker.ch/smokeping/>

L<http://www.switch.ch/misc/leinen/snmp/perl/>

The best source for background info on SAA is Cisco's documentation on L<http://www.cisco.com> and the CISCO-RTTMON-MIB documentation, which is available at: 
L<ftp://ftp.cisco.com/pub/mibs/v2/CISCO-RTTMON-MIB.my>

=cut