=head1 NAME

Smokeping::probes::EchoPingDNS - an echoping(1) probe for SmokePing

=head1 OVERVIEW

Measures DNS roundtrip times for SmokePing with the echoping_dns plugin. 

=head1 SYNOPSIS

 *** Probes ***

 +EchoPingDNS

 binary = /usr/bin/echoping
 forks = 5
 offset = 50%
 step = 300

 # The following variables can be overridden in each target section
 dns_request = example.org # mandatory
 dns_tcp = yes
 dns_type = AAAA
 extraopts = -some-letter-the-author-did-not-think-of
 ipversion = 4
 pings = 5
 plugin = /path/to/dns.so
 pluginargs = -p plugin_specific_arg
 priority = 6
 timeout = 1
 tos = 0xa0
 waittime = 1

 # [...]

 *** Targets ***

 probe = EchoPingDNS # if this should be the default probe

 # [...]

 + mytarget
 # probe = EchoPingDNS # if the default probe is something else
 host = my.host
 dns_request = example.org # mandatory
 dns_tcp = yes
 dns_type = AAAA
 extraopts = -some-letter-the-author-did-not-think-of
 ipversion = 4
 pings = 5
 plugin = /path/to/dns.so
 pluginargs = -p plugin_specific_arg
 priority = 6
 timeout = 1
 tos = 0xa0
 waittime = 1

=head1 VARIABLES

Supported probe-specific variables:

=over

=item binary

The location of your echoping binary.

Default value: /usr/bin/echoping

=item forks

Run this many concurrent processes at maximum

Example value: 5

Default value: 5

=item offset

If you run many probes concurrently you may want to prevent them from
hitting your network all at the same time. Using the probe-specific
offset parameter you can change the point in time when each probe will
be run. Offset is specified in % of total interval, or alternatively as
'random', and the offset from the 'General' section is used if nothing
is specified here. Note that this does NOT influence the rrds itself,
it is just a matter of when data acqusition is initiated.
(This variable is only applicable if the variable 'concurrentprobes' is set
in the 'General' section.)

Example value: 50%

=item step

Duration of the base interval that this probe should use, if different
from the one specified in the 'Database' section. Note that the step in
the RRD files is fixed when they are originally generated, and if you
change the step parameter afterwards, you'll have to delete the old RRD
files or somehow convert them. (This variable is only applicable if
the variable 'concurrentprobes' is set in the 'General' section.)

Example value: 300

=back

Supported target-specific variables:

=over

=item dns_request

The DNS request (domain name) to be queried.

Example value: example.org

This setting is mandatory.

=item dns_tcp

The echoping_dns '--tcp' option: use only TCP ('virtual circuit').
Enabled if specified with a value other than 'no' or '0'.

Example value: yes

=item dns_type

The echoping_dns '-t' option: type of data requested (NS, A, SOA etc.) 

Example value: AAAA

Default value: A

=item extraopts

Any extra options specified here will be passed unmodified to echoping(1).

Example value: -some-letter-the-author-did-not-think-of

=item ipversion

The IP protocol used. Possible values are "4" and "6". 
Passed to echoping(1) as the "-4" or "-6" options.

Example value: 4

=item pings

How many pings should be sent to each target, if different from the global
value specified in the Database section. Note that the number of pings in
the RRD files is fixed when they are originally generated, and if you
change this parameter afterwards, you'll have to delete the old RRD
files or somehow convert them.

Example value: 5

=item plugin

The echoping plugin that will be used. See echoping(1) for details.
This can either be the name of the plugin or a full path to the
plugin shared object.

Example value: /path/to/dns.so

Default value: dns

=item pluginargs

Any extra arguments needed by the echoping plugin specified with the 
I<pluginname> variable. These are generally provided by the subclass probe.

Example value: -p plugin_specific_arg

=item priority

The "-p" echoping(1) option.

Example value: 6

=item timeout

The "-t" echoping(1) option.

Example value: 1

Default value: 5

=item tos

The "-P" echoping(1) option.

Example value: 0xa0

=item waittime

The "-w" echoping(1) option.

Example value: 1

=back


=head1 AUTHORS

Niko Tyni <ntyni@iki.fi>

=head1 NOTES

The I<fill>, I<size> and I<udp> EchoPing variables are not valid.

Plugins, including echoping_dns, are available starting with echoping version 6.

=head1 SEE ALSO

L<Smokeping::probes::EchoPing>, 
L<Smokeping::probes::EchoPingPlugin>

=cut