/* ************************************************************************

   qooxdoo - the new era of web development

   http://qooxdoo.org

   Copyright:
     2004-2007 by 1&1 Internet AG, Germany, http://www.1und1.de

   License:
     LGPL: http://www.gnu.org/licenses/lgpl.html
     EPL 1.0: http://www.eclipse.org/org/documents/epl-v10.php

   Authors:
     * Sebastian Werner (wpbasti)
     * Andreas Ecker (ecker)
     * Fabian Jakobs (fjakobs)

************************************************************************ */

/* ************************************************************************



************************************************************************ */

/*
WARNING: This file is generated by the gettext tools from ./source/translation/en.po. Do not edit it by hand.
*/

qx.locale.Locale.define("Tr.translation.en",
{
  "Last [ms]": "Last [ms]",
  "Worst [ms]": "Worst [ms]",
  "SmokeTrace is part of the SmokePing suite created by Tobi Oetiker, Copyright 2008.": "SmokeTrace is part of the SmokePing suite created by Tobi Oetiker, Copyright 2008.",
  "Avg [ms]": "Avg [ms]",
  "Ip": "Ip",
  "Stop": "Stop",
  "Best [ms]": "Best [ms]",
  "Delay": "Delay",
  "Stopping": "Stopping",
  "Host": "Host",
  "StDev [ms]": "StDev [ms]",
  "Hop": "Hop",
  "Go": "Go",
  "Loss [%]": "Loss [%]",
  "Starting": "Starting",
  "Rounds": "Rounds",
  "Sent": "Sent"
});